name: Google Sheets Data Reader

on:
  workflow_dispatch:

jobs:
  read-sheets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
    
      
      - name: Read and Print Google Sheets Data
        run: |
          python Scripts/ReadSheets.py
